image: openjdk:8-jdk

variables:
  TARGET_SDK: "26"
  SDK_TOOLS_VERSION: "3859397" # Find latest at: https://developer.android.com/studio/index.html#downloads
  GCLOUD_SDK_VERSION: "183.0.0" # Find latest at: https://cloud.google.com/sdk/docs/quickstart-linux#before-you-begin

  ANDROID_SDK_ROOT: "/opt/android-sdk"
  ANDROID_HOME: "${ANDROID_SDK_ROOT}"
  GCLOUD_SDK_ROOT: "/opt/google-cloud-sdk"
  APK_DIR: "${CI_PROJECT_DIR}/nirvana/build/outputs/apk"
  JACOCO_REPORT_DIR: "${CI_PROJECT_DIR}/nirvana/build/reports/jacoco/debug"

  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - assemble
  - test
  - coverage
  - release

.apt-get-packages: &apt-get-packages apt-get -qq update --yes && apt-get -qq install --yes wget unzip tar sed git openssh-client

# Jobs that require the Android SDK
.require-android-sdk: &require-android-sdk
  before_script:
    - *apt-get-packages
    # Install Android SDK
    - wget --quiet --output-document=/tmp/android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${SDK_TOOLS_VERSION}.zip
    - unzip -q /tmp/android-sdk.zip -d ${ANDROID_SDK_ROOT}
    - mkdir --parents ~/.android && echo "count=0" > ~/.android/repositories.cfg
    # Install dependencies
    - mkdir --parents ${ANDROID_SDK_ROOT}/licenses/ && touch ${ANDROID_SDK_ROOT}/licenses/android-sdk-license
    - echo d56f5187479451eabf01fb78af6dfcb131a6481e > ${ANDROID_SDK_ROOT}/licenses/android-sdk-license
    - echo 84831b9409646a918e30573bab4c9c91346d8abd > ${ANDROID_SDK_ROOT}/licenses/android-sdk-preview-license
    - echo 33b6a2b64607f11b759f320ef9dff4ae5c47d97a > ${ANDROID_SDK_ROOT}/licenses/google-gdk-license
    - echo 601085b94cd77f0b54ff86406957099ebe79c4d6 > ${ANDROID_SDK_ROOT}/licenses/android-googletv-license
    - echo e9acab5b5fbb560a72cfaecce8946896ff6aab9d > ${ANDROID_SDK_ROOT}/licenses/mips-android-sysimage-license
    - ${ANDROID_SDK_ROOT}/tools/bin/sdkmanager "platforms;android-${TARGET_SDK}" "extras;google;google_play_services" "extras;google;m2repository" "extras;android;m2repository"
    # Secrets
    - echo ${APK_SIGNING_INFORMATION} > ${CI_PROJECT_DIR}/keystore.properties
    - echo ${PLAY_PUBLISH_AUTH_KEY} > ${CI_PROJECT_DIR}/nirvana/play-publish-auth-key.json
    - echo ${GOOGLE_SERVICES_CONFIG} > ${CI_PROJECT_DIR}/nirvana/google-services.json
    - echo ${FIREBASE_CRASHREPORTING_AUTH_KEY} > /tmp/firebase-crashreporting-auth-key.json
  after_script:
    # Wipe the secrets
    - rm --force ${CI_PROJECT_DIR}/keystore.properties ${CI_PROJECT_DIR}/nirvana/play-publish-auth-key.json ${CI_PROJECT_DIR}/nirvana/google-services.json /tmp/firebase-crashreporting-auth-key.json

# Jobs that require the Google Cloud SDK
.require-google-cloud-sdk: &require-google-cloud-sdk
  before_script:
    - *apt-get-packages
    # Install Google Cloud SDK
    - wget --quiet --output-document=/tmp/gcloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${GCLOUD_SDK_VERSION}-linux-x86_64.tar.gz
    - tar --extract --file /tmp/gcloud-sdk.tar.gz --directory /opt
    # Authentication
    - echo ${GCLOUD_PROJECT_AUTH_KEY} > /tmp/gcloud-project-auth-key.json
    - ${GCLOUD_SDK_ROOT}/bin/gcloud auth activate-service-account --key-file /tmp/gcloud-project-auth-key.json
  after_script:
    # Wipe the authentication key
    - rm --force /tmp/gcloud-project-auth-key.json

# Jobs that run instrumental tests on Firebase
.run-firebase-instrumental-test: &run-firebase-instrumental-test
  dependencies:
    - assemble:debug
  script:
    - >
        ${GCLOUD_SDK_ROOT}/bin/gcloud firebase test android run --project nirvana-app --type instrumentation
        --app ${APK_DIR}/debug/nirvana-debug.apk
        --test ${APK_DIR}/androidTest/debug/nirvana-debug-androidTest.apk
        --device model=${VIRTUAL_DEVICE},version=${API_LEVEL},locale=en,orientation=portrait
        --device model=${PHYSICAL_DEVICE},version=${API_LEVEL},locale=en,orientation=portrait

# Jobs that run robo tests on Firebase
.run-firebase-robo-test: &run-firebase-robo-test
  dependencies:
    - assemble:debug
  script:
    - >
        ${GCLOUD_SDK_ROOT}/bin/gcloud firebase test android run --project nirvana-app --type robo
        --app ${APK_DIR}/debug/nirvana-debug.apk
        --device model=${VIRTUAL_DEVICE},version=${API_LEVEL},locale=en,orientation=portrait
        --device model=${PHYSICAL_DEVICE},version=${API_LEVEL},locale=en,orientation=portrait

# Assemble -debug.apk & -debug-androidTest.apk
assemble:debug:
  stage: assemble
  script:
    - ${CI_PROJECT_DIR}/gradlew assembleDebug assembleDebugAndroidTest
  artifacts:
    paths:
    - ${APK_DIR}
  <<: *require-android-sdk

# Run local unit tests
test:unit:
  stage: test
  script:
    - ${CI_PROJECT_DIR}/gradlew testDebugUnitTest jacocoTestReportDebug
  artifacts:
    paths:
      - ${JACOCO_REPORT_DIR}
  <<: *require-android-sdk

# Run instrumental tests on Firebase against API 24
test:instrumental:api24:
  stage: test
  variables:
    API_LEVEL: "24"
    VIRTUAL_DEVICE: "Nexus5X"
    PHYSICAL_DEVICE: "herolte"
  <<: *require-google-cloud-sdk
  <<: *run-firebase-instrumental-test

# Run instrumental tests on Firebase against API 26
test:instrumental:api26:
  stage: test
  variables:
    API_LEVEL: "26"
    VIRTUAL_DEVICE: "Nexus5X"
    PHYSICAL_DEVICE: "sailfish"
  <<: *require-google-cloud-sdk
  <<: *run-firebase-instrumental-test

# Run robo tests on Firebase against API 25
test:robo:api25:
  stage: test
  when: manual
  variables:
    API_LEVEL: "25"
    VIRTUAL_DEVICE: "Nexus5X"
    PHYSICAL_DEVICE: "sailfish"
  <<: *require-google-cloud-sdk
  <<: *run-firebase-robo-test

# Collect code coverage
jacoco:
  stage: coverage
  when: always
  dependencies:
    - test:unit
  script:
    - test -f "${JACOCO_REPORT_DIR}/index.html" && cat "${JACOCO_REPORT_DIR}/index.html"
  coverage: /'Total.*?([0-9]{1,3})%'/

# Release to Google Play alpha track
release:alpha:
  stage: release
  when: manual
  script:
    - mkdir --parents ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr --delete '\r' | ssh-add - > /dev/null
    - git config --global user.email "ci@leesah.name"
    - git config --global user.name "GitLab-CI"
    - sed --regexp-extended --in-place 's/^(versionCode=)([0-9]+)$/echo "\1$((\2+1))"/ge' ${CI_PROJECT_DIR}/version.properties
    - sed --regexp-extended 's/^(versionCode)=([0-9]+)$/echo "[GitLab-CI] Stepping \1 to \2"/ge' ${CI_PROJECT_DIR}/version.properties | xargs -I{} git commit --message="{}" --message="[skip ci]" ${CI_PROJECT_DIR}/version.properties
    - git push
    - ${CI_PROJECT_DIR}/gradlew clean assembleRelease publishApkRelease
    - ${CI_PROJECT_DIR}/gradlew -PFirebaseServiceAccountFilePath=/tmp/firebase-crashreporting-auth-key.json :nirvana:firebaseUploadReleaseProguardMapping
  artifacts:
    paths:
    - ${APK_DIR}
    - ${CI_PROJECT_DIR}/nirvana/build/outputs/mapping
  <<: *require-android-sdk
